version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app_network


  db:
    image: postgres:16
    ports:
      - "5433:5432"
    env_file:
      - .env
    networks:
      - app_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  app_network:
    driver: bridge
volumes:
  postgres_data: