spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:${DB_DRIVER}://${DB_HOST}:${PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  mvc:
    view:
      prefix: /templates/
      suffix: .html

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show_sql: true

  liquibase:
    enabled: true
    changelog: db/changelog/db.changelog-master.yml

  cloud:
    openfeign:
      client:
        config:
          openWeatherClient:
            connect-timeout: 10000
            read-timeout: 15000
            url: https://api.openweathermap.org
            logger-level: basic
            default-query-parameters:
              limit: 15
              appid: ${OPEN_WEATHER_KEY}
open-weather-api:
  geo-path: /geo/1.0/direct
  weather-path: /data/2.5/weather