spring:
  profiles:
    active: test
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  cloud:
    openfeign:
      client:
        config:
          openWeatherClient:
            connect-timeout: 10000
            read-timeout: 15000
            url: https://api.openweathermap.org
            logger-level: basic
            default-query-parameters:
              limit: 15
              appid: ${OPEN_WEATHER_KEY}
---
#dev config
spring:
  config:
    activate:
      on-profile: dev

open-weather-api:
  geo-path: /geo/1.0/direct
  weather-path: /data/2.5/weather
  units: metric

jakarta:
  persistence:
    jdbc:
      driver: org.postgresql.Driver
      url: jdbc:postgresql://${DB_HOST_DEV}:${DB_PORT_DEV}/weather_app_database
      user: ${DB_USER_DEV}
      password: ${DB_PASSWORD_DEV}
hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show-sql: true
  format-sql: true
  hbm2ddl:
    auto: validate

session:
  maxAge: 604_800
  cleanup:
    cron: 0 0 3 * * SUN
cookie:
  maxAge: 604_800

logging:
  level:
    web: debug

---
#test config
spring:
  config:
    activate:
      on-profile: test

session:
  maxAge: 604_800
  cleanup:
    cron: 0 0 3 * * SUN
cookie:
  maxAge: 604_800

jakarta:
  persistence:
    jdbc:
      driver: org.h2.Driver
      url: jdbc:h2:mem:test_db
      user: sa
      password:
hibernate:
  dialect: org.hibernate.dialect.H2Dialect
  show-sql: true
  format-sql: true
  hbm2ddl:
    auto: create

